### ISSUE TITLE
How to set FilePath property?

### ISSUE THREAD

**Issue by claym** [MscrmTools/MsCrmTools.WebResourcesManager#10]
When I try to run "Refresh from disk" on a javascript resource, I get an error that states

"Cannot refresh from disk is FilePath property is not set for the web resource"

How do I set (permanently) that FilePath?

**Comment by MscrmTools** [comment]
The file path is set when you save files to disk or when you load web resources from disk

**Comment by claym** [comment]
Ah ok - it seems it doesn't retain the path if you do an "Update web resources from local file"

I'm yet to figure out a workflow that lets me grab the webresources from CRM and then sync between my local VS project's files without having to enter the path every time i need to update.

Am I missing something?

Thanks!

**Comment by claym** [comment]
Any ideas? Having to paste the folder directory in every time I hit the "update web resources" button is pretty obnoxious :D

**Comment by daryllabar** [comment]
I always work from TFS, and open my code using the File --> Load Webresources option.  Then If I update a file outside of the XTB, I just right click and refresh from disk.

**Comment by MscrmTools** [comment]
@claym is this issue fixed? I guess so but would like your confirmation
