### ISSUE TITLE
Could not load the Scintilla Module 

### ISSUE THREAD

**Issue by eccountable** [MscrmTools/MsCrmTools.WebResourcesManager#100]
When I try to open a JS or HTML web resource, I get an error message 
Could not load the Scintilla Module at the path 'c:\users\...\AppData\Local\Temp\ScintillaNet\3.6.3\x64\SciLexer.dll'

I have uninstalled/reinstalled the WebResources Manager module. 

WebResources Manger v 2.2020.5.12
using XRMToolbox v 1.2020.6.40

**Comment by MscrmTools** [comment]
If using both latest version of XrmToolBox and webresources manager, you shouldn't get this error message.
Scintilla assembly should be included in XrmToolBox installation folder. Can you check the assembly is there?

**Comment by eccountable** [comment]
never mind. a reboot fixed it.
