### ISSUE TITLE
Error loading webresources in CRM 2013

### ISSUE THREAD

**Issue by k-babich95** [MscrmTools/MsCrmTools.WebResourcesManager#101]
An exception occured while retrieving webresources: 'WebResource' entity doesn't contain attribute with Name = 'dependencyxml'.

[webresourcemanager-tracelog.txt](https://github.com/MscrmTools/MsCrmTools.WebResourcesManager/files/5332207/webresourcemanager-tracelog.txt)

![image](https://user-images.githubusercontent.com/51298393/95175182-ca5c5d00-07c3-11eb-9e7d-29616a7f6f61.png)

**Comment by MscrmTools** [comment]
What version of CRM/D365/CDS are you targeting?
