### ISSUE TITLE
High memory usage ~ 3 GB committed memory and Private memory loading all JavaScript web resources for a Dyn 365 online org ~ 100 web resources

### ISSUE THREAD

**Issue by crexin** [MscrmTools/MsCrmTools.WebResourcesManager#102]
I'm seeing very high memory usage for the XRMToolbox.exe when just using the Webresources manager connecting to Dynamics 365 online and selecting to load all web resources and unchecking everything but the js web resources. Memory usage is close to 3 GB for both committed and private bytes.  I then see hangs in the application after selecting all the web resources and choosing File - Save all files with checked 
![XRMToolbox_WebResourcesJS_HighMemUsage](https://user-images.githubusercontent.com/6042229/98167319-7fab2f00-1eae-11eb-8858-7dea90a73b3a.png)  Note that it was able to finish the save operation if I saved locally, but had hung when I tried saving to OneDrive for Business, which is where I typically export backups of these files to (and haven't had an issue before)

---
![XRMToolbox_WebResourcesJS_HighMemUsage](https://user-images.githubusercontent.com/6042229/98167508-cc8f0580-1eae-11eb-9ebd-c6a69803930e.png)

- Deployment: Online
- DB Version: 9.1.0.24055
- Connection Controls Version: 1.2020.10.35
- XrmToolBox Version: 1.2020.10.41
- Tool Version: 2.2020.5.12

**Comment by MscrmTools** [comment]
I'm not sure that would be a good practice to load all web resources, without any filter

**Comment by MscrmTools** [comment]
There is a new feature to lazy load web resources which should reduce the overall amount of memory used.

<img width="307" alt="image" src="https://user-images.githubusercontent.com/10774317/151970290-135862a9-98ba-4819-b8af-2d1433904c7f.png">


So I'm closing this issue
