### ISSUE TITLE
SVG Support

### ISSUE THREAD

**Issue by donalmc** [MscrmTools/MsCrmTools.WebResourcesManager#104]
Power Platform apps require SVGs for Site Maps, but the XRM plugin does not seem to work with them - unless I am missing something?

Thanks

**Comment by MscrmTools** [comment]
I don't know what version you are using but SVG are supported since many months

**Comment by donalmc** [comment]
Hi
Thanks for quick reply. It looks like I am using an up-to-date version but it won't let me select SVGs for uploading

![image](https://user-images.githubusercontent.com/4288638/109002867-adef8d00-769e-11eb-8106-0a1f41e8a91f.png)

**Comment by MscrmTools** [comment]
oh, I see, I might have forgot to update this specific screen... I will do

**Comment by MscrmTools** [comment]
New release will come shortly
