### ISSUE TITLE
Add setting to "Include" prefixes

### ISSUE THREAD

**Issue by kschepperly** [MscrmTools/MsCrmTools.WebResourcesManager#106]
Deployment: On-Premise
DB Version: 8.2.1.342
XrmToolBox Version: 1.2021.2.45
Tool Version: 2.2021.2.15

Would it be possible to add a new setting to INCLUDE specific prefixes prior to loading? This would work exactly like the existing setting to EXCLUDE prefixes.

Our deployment contains many custom prefixes due to third party solutions over time, and we leverage the exclude prefixes setting as well as the recently added lazy loading setting, but often I am only working with our primary internal prefix and would like to be able to simply specify that single prefix to include rather than list upwards of 10-15 custom exclusion prefixes.

**Comment by MscrmTools** [comment]
Totally possible! I will work on adding this

**Comment by MscrmTools** [comment]
Added in latest version that will be available very soon
