### ISSUE TITLE
Invalid DockState

### ISSUE THREAD

**Issue by SopraSteriaDK-Miller** [MscrmTools/MsCrmTools.WebResourcesManager#107]
Unable to open tool due to an invalid DockState.

Complete error message:
![image](https://user-images.githubusercontent.com/82498838/114670099-f3295600-9d02-11eb-84dc-a44ad56a78da.png)

**Comment by SopraSteriaDK-Miller** [comment]
Fixed by deleting the existing settings file, from %USERPROFILE%\AppData\Roaming\MscrmTools\XrmToolBox\Settings.

The corrupted file looked like this:
[_MscrmTools.WebresourcesManager.zip](https://github.com/MscrmTools/MsCrmTools.WebResourcesManager/files/6309114/_MscrmTools.WebresourcesManager.zip)

**Comment by MscrmTools** [comment]
Thnak you for reporting. I will add a check to auto fix settings when this situation happens

**Comment by MscrmTools** [comment]
Will be fixed in latest version
