### ISSUE TITLE
Sub Folders not loading for local files

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/MsCrmTools.WebResourcesManager#111]
It used to be when you select File --> Load Web Resources, it would load all sub folders.  Currently this not the case.  Only the selected folder is loaded.

**Comment by MscrmTools** [comment]
Well, [this code](https://github.com/MscrmTools/MsCrmTools.WebResourcesManager/blob/master/MsCrmTools.WebResourcesManager/AppCode/Webresource.BulkStatic.cs#L339) seems to do the recursivity...
I will double check and try to reproduce

**Comment by MscrmTools** [comment]
I just tried with latest version and it did work...
![image](https://user-images.githubusercontent.com/10774317/117693483-6026f300-b1be-11eb-8f54-b0d9c18cfafb.png)

**Comment by MscrmTools** [comment]
Ok, i got it, I'm only processing sub folders under a folder with a underscore at the end of the folder as a customization prefix is kind of required to generate the unique name of the web resource

**Comment by daryllabar** [comment]
Guess it's time to donate to the facepalm jar...
