### ISSUE TITLE
Error launching plugin

### ISSUE THREAD

**Issue by ChrisKoenig** [MscrmTools/MsCrmTools.WebResourcesManager#116]
I receive the following error message when opening the app:

An error occurred when trying to display this tool: Invalid DockState: Content can not be showed as "Unknown" or "Hidden".

plugin version: 2.2021.5.18
app version 1.2021.9.52

**Comment by MscrmTools** [comment]
@ChrisKoenig, You should delete the settings file for Webresources manager tool

**Comment by ChrisKoenig** [comment]
that worked - thanks!
________________________________
