### ISSUE TITLE
XRMToolbox Web Resource Manager Plugin Invalid file extension

### ISSUE THREAD

**Issue by bipinshan** [MscrmTools/MsCrmTools.WebResourcesManager#117]
Hi Experts,

We have a requirement to checkin all web resources from Dynamics CRM to Source control. And as part of this requirement we have decided to use XRMToolbox Web Resource Manager Plugin.

https://github.com/MscrmTools/MsCrmTools.WebResourcesManager

The problem which I am facing is with File Extension when I export web resources files to local drive. As you can see in below image, I have few JS which does not .js extension in web resource name and one has the extension. Now When I export the files to local drive I don't see the correct file extension for javascript and because of this I will face issues while editing this file from Visual studio.
![image](https://user-images.githubusercontent.com/3380476/150529599-4cb05e05-d5df-410b-98a1-d79f11355920.png)

![image](https://user-images.githubusercontent.com/3380476/150529582-4319d275-7682-485a-8dbe-05799805a40f.png)

Need your help and guidance on how to fix this particula issue.

Thanks,

Bipin

**Comment by MscrmTools** [comment]
Hi @bipinshan, you should be able to fix this by using the appropriate setting
![image](https://user-images.githubusercontent.com/10774317/150541906-f4060b29-c120-4925-b20a-73b866773252.png)

**Comment by bipinshan** [comment]
Hi @MscrmTools ,

Thank you for your reply!

I did updated the setting which you mentioned to True but still same issue.
![image](https://user-images.githubusercontent.com/3380476/150548299-3dda77c5-5863-41b1-95eb-770d56545d1d.png)

Do I need to update any other settings to resolve my issue?

Appreciate your help!
Thanks,
Bipin

**Comment by MscrmTools** [comment]
Indeed, it seems this settings is not honored when exporting files to disk.
Can you try with this version [MscrmTools.WebresourcesManager.zip](https://github.com/MscrmTools/MsCrmTools.WebResourcesManager/files/7914725/MscrmTools.WebresourcesManager.zip) ?

**Comment by bipinshan** [comment]
Hi @MscrmTools ,

It works.

When do we expect this to be imcluded in latest version of plugin?

Thanks,
Bipin

**Comment by MscrmTools** [comment]
I need to check if other issues have to be fixed. Will try that next week

**Comment by bipinshan** [comment]
Hi @MscrmTools ,

Thank you so much for your help!!
