### ISSUE TITLE
Error while opening a webresource

### ISSUE THREAD

**Issue by MscrmTools** [MscrmTools/MsCrmTools.WebResourcesManager#12]
@con-ssc commented on [Mon Oct 10 2016](https://github.com/MscrmTools/XrmToolBox/issues/501)

I get an initial error when I open a webresource in the webresource manager

![image](https://cloud.githubusercontent.com/assets/8189808/19230111/ed078f64-8ed2-11e6-87a8-431d67f3f855.png)

**Comment by daryllabar** [comment]
Here is the English version f the error

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at MsCrmTools.WebResourcesManager.New.UserControls.WebresourceTreeView.get_SelectedResource()
>    at MsCrmTools.WebResourcesManager.New.UserControls.WebresourceTreeView.Tv_NodeMouseClick(Object sender, TreeNodeMouseClickEventArgs e)
>    at System.Windows.Forms.TreeView.OnNodeMouseClick(TreeNodeMouseClickEventArgs e)
>    at System.Windows.Forms.TreeView.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>

**Comment by MscrmTools** [comment]
Did you update to last version? It should be fixed now

**Comment by daryllabar** [comment]
Doh!  This was listed as open, and so I didn't even think about checking it...

**Comment by MscrmTools** [comment]
I should have closed the issue
