### ISSUE TITLE
Feature request: filter for pending changes

### ISSUE THREAD

**Issue by YoYoFreakCJ** [MscrmTools/MsCrmTools.WebResourcesManager#120]
I'd like a setting to filter the web resources shown in the pending changes.

map files are often generated by transpilers which we have to uncheck everytime which is bothersome. So I'd like to filter for map files and eventually other files by providing a setting which allows for search terms to filter for using wildcards.

I actually implemented this feature already. If you allowed me to create a branch you could review it and eventually just merge it to the master.

Without setting:
![grafik](https://user-images.githubusercontent.com/59722190/190371292-26272ecd-68d1-4333-89f6-a6dd215a7ec6.png)

With setting:
![grafik](https://user-images.githubusercontent.com/59722190/190370907-014c4ac3-e798-4dec-aaea-635e658f76af.png)
![grafik](https://user-images.githubusercontent.com/59722190/190371388-bf336f4e-53e0-4d49-94b4-76b4bd0e479d.png)

**Comment by MscrmTools** [comment]
If you forked this repo, then you can create a pull request so that I can merge your change

**Comment by MscrmTools** [comment]
I have merged your pull request. Thank you
