### ISSUE TITLE
Open the Web Resources in Collapse mode  by default

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/MsCrmTools.WebResourcesManager#13]
When I load my files from disk, it defaults to showing all files and folders expanded.  I always have to collapse all.  Thoughts to defaulting the tree view to collapsed if there are more than a certain number of files, or potentially having a setting, or potentially remembering what button you clicked last, collapse all or expand all, and opening up with that default.

All Ideas.

**Comment by MscrmTools** [comment]
Will be fixed soon
