### ISSUE TITLE
New Root with not publisher with that root prefix

### ISSUE THREAD

**Issue by con-ssc** [MscrmTools/MsCrmTools.WebResourcesManager#15]
I ran into the problem that I could not load all webresources nor the ones from specific solution with that files in when I made a root that no publisher had a matching prefix to.

**Comment by MscrmTools** [comment]
This is not the problem, I am able to save an load web resources with a prefix not known as a publisher prefix.
The problem is with web resources saved without any content. The issue will be fixed very soon
