### ISSUE TITLE
When Loading files from CRM, htm files are missing...

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/MsCrmTools.WebResourcesManager#17]
"Html" files are being loaded correctly, but "htm" files are not being returned when loading from CRM

**Comment by MscrmTools** [comment]
I will add this.

BTW, why htm even exists??? does Hyper Text Markup means anything without Language?

**Comment by daryllabar** [comment]
http://stackoverflow.com/questions/1163738/htm-vs-html
I don't know.  In the future I'm probably going to switch over to html, but there was a managed solution that I was trying to figure out, that was using htm...

**Comment by MscrmTools** [comment]
ok, for you, just for you :) I will do it now!

**Comment by daryllabar** [comment]
Thanks...  I'll transfer 1000000 internetz to your account...

**Comment by MscrmTools** [comment]
wait... I can't find any reference to htm(l) in the code for loading web resources from CRM... so I don't know what to fix...

**Comment by daryllabar** [comment]
ehh...  I don't really need this right now..  Just noticed it wasn't working...

**Comment by MscrmTools** [comment]
sure but I can't find where the problem is... well, I guess I just have to create a web resource manually with a htm extension and see how it behaves

**Comment by MscrmTools** [comment]
so I just tested and htm files are loaded correctly...

**Comment by daryllabar** [comment]
hmm.. You're right...  I'm not sure what is going on then, because I have a managed solution that is displaying a web-resource that is an htm file, but I don't see it in the Web Resource Manager or the Default solution (other htm files are showing up).

I'm going to close this, and hopefully figure out what the heck is going on...

**Comment by MscrmTools** [comment]
If the web resource is set as not editable by the owner (in managed properties) , then you cannot see it otherwise than extracting from dB (if you are onpremise)

**Comment by daryllabar** [comment]
I learn something new every day!
