### ISSUE TITLE
Make Refreshing From Disk easier

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/MsCrmTools.WebResourcesManager#19]
I write in Typescript in Visual Studio, which when saved, generate JavaScript files. I then use the Load from from disk functionality to load my JS files.  Problem is, every time I want to update my file, I have to right-click, then select refresh from disk, then right click, then select Save and Publish to Server:

![image](https://cloud.githubusercontent.com/assets/9728423/22309292/a7d4ff86-e318-11e6-8740-5e6db2bc39ca.png)

Ideally, when I load files from disk, the Web Manager would add file watchers for all files, and when they change, it would ask me if I want to update and publish all files that have changed.  

As a maybe easier/intermediate step, if there was a short cut key to refresh from disk, let's say "ctrl-d" ,then I could just select my file , and do "ctrl-d", "ctrl-u" in order to refresh and then update my file

**Comment by MscrmTools** [comment]
@daryllabar I'll add the intermediate step first :)

nevertheless Ctrl+D is already binded in the TextEditor component so I have to use Ctrl+Shift+D. Is it a problem?

**Comment by daryllabar** [comment]
Ctrl-r?

**Comment by MscrmTools** [comment]
already used for Replace feature

**Comment by daryllabar** [comment]
Ctrl+Shift+D will work then.  Or maybe make publish Ctrl-p?

**Comment by MscrmTools** [comment]
I switched the Ctrl+R, so you can use it

The new version is online

**Comment by daryllabar** [comment]
![71d65c1595a0c0cf147eb1c4387cac3aa1f8952ea8466a5be294f404d15d9cc4 1](https://cloud.githubusercontent.com/assets/9728423/24204766/d9d7c362-0eef-11e7-92f4-866ef70190e7.jpg)
