### ISSUE TITLE
Set The Disk path

### ISSUE THREAD

**Issue by aboodh95** [MscrmTools/MsCrmTools.WebResourcesManager#24]
Hi
How can i set the path of the file on the disk
all the time the Text box is Disabled

**Comment by MscrmTools** [comment]
The path is set if you load the file(s) from disk or if you save the web resources to disk

**Comment by aboodh95** [comment]
can you make it adjustable

**Comment by MscrmTools** [comment]
which means? What would you like to be able to do?

**Comment by aboodh95** [comment]
set the path manual

**Comment by MscrmTools** [comment]
I don't see the point... If the file is on your disk, load it from there and the path will be set.

If the webresource is not on your disk, the path is not necessary. If you save the webresource to the disk, the path will be automatically filled

**Comment by aboodh95** [comment]
OK Thank you
