### ISSUE TITLE
Issues loading the default sitemap

### ISSUE THREAD

**Issue by xairrick** [MscrmTools/MsCrmTools.WebResourcesManager#26]
~~I have one org where the default sitemap wont load, only the sitemap from a newly created App loads (ie the sitemap selection dialog doesn't appear)~~   [UPDATE I was using a older version]

I have another org where the it shows the Sitemap selection dialog, and it lists "Default" 14 times even along with the other 4 Apps. 
![2017-04-19 15_58_26-](https://cloud.githubusercontent.com/assets/80464/25199511/140e426a-2519-11e7-9523-ef700a7c35fa.png)

**Comment by MscrmTools** [comment]
I'm aware of this bug so this is good to have it listed here.

I will work on it asap

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MscrmTools.SiteMapEditor #12](https://github.com/MscrmTools/MscrmTools.SiteMapEditor/issues/12) via [**ZenHub**](https://www.zenhub.com/)
