### ISSUE TITLE
"Control+C" not working in new version (1.2017.7.18)

### ISSUE THREAD

**Issue by aaroncarpenter** [MscrmTools/MsCrmTools.WebResourcesManager#27]
Since upgrading to the latest version, the Control+C keyboard shortcut isn't working.  Cntl+X and Cntl+V both work as expected.  As it stands now, I have to highlight and use the right-click menu to copy items.  It's possible that this is just an issue with my machine, but Cntl+C works fine in other programs on my machine.

**Comment by MscrmTools** [comment]
It's a known issue and it will be fixed in next release but I'm in holidays now so you will have to wait three weeks

**Comment by aaroncarpenter** [comment]
No worries.  Enjoy your holidays!
