### ISSUE TITLE
Replace with new file doesn't detect changes (version 1.2017.8.11)

### ISSUE THREAD

**Issue by hjmhyl** [MscrmTools/MsCrmTools.WebResourcesManager#29]
Change some code in local JavaScript file, then click Replace with new file, the web resource tab name doesn't change to red, nothing happens. if I don't upgrade to latest version, use installed version(1.2017.3.9). It works.

**Comment by BrettRojas** [comment]
I'm seeing the same issue

**Comment by larsey** [comment]
I'm having the same issue.

**Comment by MscrmTools** [comment]
I used this feature many times last week without issues... Do you save (Ctrl+S) the change after having used the Replace feature?

**Comment by bleehah** [comment]
I'm having the same issue. After replacing the file, the Save button is still disabled and no changes are detected.

**Comment by MscrmTools** [comment]
This should be fixed in the latest version
