### ISSUE TITLE
Cannot compare web resources (version 1.2017.8.11)

### ISSUE THREAD

**Issue by Kraviecc** [MscrmTools/MsCrmTools.WebResourcesManager#30]
Hi,

I'm facing the issue that I cannot successfully run compare tool from within web resource manager. I set diff path and arguments but when I click compare it still shows me settings window (my values are there) with additional message "in order to...".

Could you please tell me how to use it or just fix it? 
Thanks.

**Comment by MscrmTools** [comment]
To compare, you must define first a compare tool (WinMerge, WinDiff) in the settings

**Comment by Kraviecc** [comment]
Yes, actually I did this and when I click on button to compare it still shows me the same setting window even if values in it are set.

**Comment by MscrmTools** [comment]
Ok, I'm not the one who developed this feature so I should look for the code before doing anything but I'm quite busy these days so it won't be soon

**Comment by Kraviecc** [comment]
Hey,

I've fixed this, tested and created pull request. Just look at this.
