### ISSUE TITLE
Add support for Vector Graphics (.svg) icons

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/MsCrmTools.WebResourcesManager#32]
Currently the Web Resource Manager doesn't export *.svg files when you retrieve from CRM (they aren't listed in the 'filter' dialog, and even if you select 'All', they aren't exported.

**Comment by MscrmTools** [comment]
Hi Scott, I admit I never worked with svg files... can you send me one so that I can work with it?

**Comment by MscrmTools** [comment]
forget me... I found some on the net

**Comment by mscottsewell** [comment]
I usually go here - https://www.flaticon.com/ to find icons to use for custom entities in CRM. - You can download the same icon in multiple formats, including svg - which is the format preferred for the UCI client navigation bar.

**Comment by MscrmTools** [comment]
That's the website I'm using too and found out they propose svg as format

Thanks anyway

**Comment by MscrmTools** [comment]
@mscottsewell, can you try this new version and tell me if it cover all your needs?

You just have to remove the txt extension and copy the file in your XrmToolBox Plugins folder.

I also added a new settings to add prefix for webresources that won't be loaded (like msdyn_, adx_ or cdi_, as you wish), if you can tell me your thought about this new settings, that would be great

[MsCrmTools.WebResourcesManager.dll.txt](https://github.com/MscrmTools/MsCrmTools.WebResourcesManager/files/1350045/MsCrmTools.WebResourcesManager.dll.txt)

**Comment by mscottsewell** [comment]
Hi Tanguy - it didn't seem to resolve the issue, I restarted the app and validated that the version is 1.2017.10.12 

I've made you an administrator in the org - will send you login credentials separately.
