### ISSUE TITLE
settings - what means obfuscate code

### ISSUE THREAD

**Issue by bryce2071** [MscrmTools/MsCrmTools.WebResourcesManager#33]
Hi, 

i want to obfuscate the javascript code and saw, that in XRMTB/WebResorucesManager there is a setting "JavaScript : Obfuscate code" under "Minifying".
What will be done if i set this setting?
Will there automatically done an obfuscation.
Are the thing, i can change for deepness oo obfuscation?
What if i do a obfuscation (inkl. changing function-names) .. how will i call them in the OnLoad of the different CRM-Forms and what if i have more than 1 js-file loaded in a form, f.e. a tools-js-file which i start with every different crm-form. What if i change the function names - how will the other js-file know the new (obufscated) function name?
How will i know the obfuscated name of a function, that i call in onchange of a field on form?
I still se the js as readable js? So what and where will be done something?
many many many THX, greets PeB

**Comment by MscrmTools** [comment]
Obfuscation is performed when minifying the web resource, if the settings is enabled.

I'm using an external library to handle this obfuscation so I can't really answer your question about what is obfuscated and how. You will have to try by yourself.

**Comment by bryce2071** [comment]
Thx.
It would be nice if you tell me howyou do it externally, the software you use, and how you get it done less time consuming, f.e. Batch processing maybe batch uploading or do you copy and paste every single obfuscated file into js webresource.
How have you done it that the field on form knows the obfuscated name of the onchange function...
maybe you ll find some minutes to give me a little howto start.
Thx, greetings peb

**Comment by MscrmTools** [comment]
The obfuscation is done only if you hit the Minify button. This is your choice for a single web resource to perform the code reduction.

So there is no batch, no external program, etc. There is also no change to event registration. 

So this feature is really only to minify code of a web resource. Everything else is on your side
