### ISSUE TITLE
Losing The Status of should update

### ISSUE THREAD

**Issue by aboodh95** [MscrmTools/MsCrmTools.WebResourcesManager#36]
Hi

There is an issue that in case i update a web resource but still waiting to update in the server 
![image](https://user-images.githubusercontent.com/12459798/32711209-48d5fa4c-c857-11e7-9b1d-1564ddab74da.png)

if i select another web resource from the list i will lose this status of update and i need to re edit some line to be able to update

**Comment by MscrmTools** [comment]
This should be fixed in the latest version. Can you check please?

**Comment by aboodh95** [comment]
Yes
it's fixed, Thank you
