### ISSUE TITLE
Issue with the code editor

### ISSUE THREAD

**Issue by aboodh95** [MscrmTools/MsCrmTools.WebResourcesManager#37]
Hi

I'm having issue with the code editor for web resources and for Portal code editor 

Frequently I'm getting this error 

![image](https://user-images.githubusercontent.com/12459798/33976654-f8f44b0c-e0af-11e7-8e53-9757e9413595.png)

and the quick fix will be closing the app and re oping it.
is this issue because of my pc or something with the code editor libraries

**Comment by MscrmTools** [comment]
This is an issue because of the code component. It appears only if you open both plugins in the same CRM toolbox session
Not sure I can do something about it unfortunately

**Comment by aboodh95** [comment]
Ok

Thank you
