### ISSUE TITLE
1.2018.14 showing "updated from someone else" after publishing once

### ISSUE THREAD

**Issue by aovar** [MscrmTools/MsCrmTools.WebResourcesManager#39]
Steps to repro:

1. Open any JS web resource (I was connected to a CRM 2016 v8.1 on-prem)
2. Paste code i.e. from Visual Studio
3. Update and Publish
4. Wait for it to finish
5. Update and Publish again (with or without changes to the contents of the web resource)
The "updated from someone else" dialog pops up

**Comment by MscrmTools** [comment]
Just found out myself this issue.

I will fix it today
