### ISSUE TITLE
Request to move select/unselect/collapse/expand to top

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/MsCrmTools.WebResourcesManager#4]
I'm having to constantly move my mouse all the way to the very bottom...  minor inconvenience:

Picture worth a 1000 words:
![screenshot](https://cloud.githubusercontent.com/assets/9728423/17521209/84ff2856-5e20-11e6-8562-36fa0fac70ff.jpg)

**Comment by MscrmTools** [comment]
ok, will do it
