### ISSUE TITLE
Update and Publish empties the web resource instead

### ISSUE THREAD

**Issue by aovar** [MscrmTools/MsCrmTools.WebResourcesManager#40]
Afflicted version: v1.2018.1.20
Connected to a Dynamics 365 v9.0 organization
Severity: Medium/High

Unfortunately I haven't figured out how to predictably reproduce the issue, it could be either random or tied to a particular succession of actions.

What happens is, I copy/paste the content of the web resource from Visual Studio into the Web Resource, do CTRL+S CTRL+U to save, update and publish it, and the web resource on the CRM ends up being empty instead.

I took the habit to double check after every publish to make sure the code is still there by closing the web resource tab and reloading it... 

Also, when the tab comes up empty and I re-copy/paste the code, upon doing CTRL+U to update and publish a popup comes up to tell me the WS was changed on the server (I click "yes" and usually the code is published correctly afterwards).

It seems to be more likely to happen if I update and publish several web resources in succession.

**Comment by MscrmTools** [comment]
I already faced this situation once but can't tell exactly, like you, what leads to this behavior.
As I'm using this plugin regulalry, I will pay attention to this bug

**Comment by MscrmTools** [comment]
I don't think so...

**Comment by MscrmTools** [comment]
Closing as I never reproduced again
