### ISSUE TITLE
JavaScript beautify not working properly (Plugin Version - 1.2018.3.17)

### ISSUE THREAD

**Issue by Divjyot1** [MscrmTools/MsCrmTools.WebResourcesManager#42]
Plugin Version - 1.2018.3.17

Thanks.

**Comment by MscrmTools** [comment]
What do you mean by not working properly? Please describe

**Comment by Divjyot1** [comment]
Two Code snippets showing before and after beautification
![webresource issue](https://user-images.githubusercontent.com/36576126/38081271-3d144504-3361-11e8-969a-e4c503d57524.png)

Thanks

**Comment by MscrmTools** [comment]
Ok, thanks for these info

**Comment by MscrmTools** [comment]
Fixed in latest version
