### ISSUE TITLE
Line Numbers Display 3 Digits Only

### ISSUE THREAD

**Issue by yuvalrs** [MscrmTools/MsCrmTools.WebResourcesManager#44]
The text editor line number length is limited to 3 digits.
For example: line 1234  is displayed as 234

For example - see the following picture:
Line  6850 displayed as line 850
![03-jun-18 21-52-43](https://user-images.githubusercontent.com/5218628/40890150-039dfb92-677a-11e8-8fa9-ac5c81a6f75f.jpg)

Yuval R.

**Comment by MscrmTools** [comment]
Fixed
