### ISSUE TITLE
Unhanded Exception: Value cannot be null

### ISSUE THREAD

**Issue by yuvalrs** [MscrmTools/MsCrmTools.WebResourcesManager#45]
Selecting  'Compare/Settings' 
![03-jun-18 22-11-07](https://user-images.githubusercontent.com/5218628/40890283-58c7c8a8-677c-11e8-9e49-b673b9777693.jpg)

yields the following exception
![03-jun-18 22-12-02](https://user-images.githubusercontent.com/5218628/40890282-58a735ac-677c-11e8-8dd1-bbc56b920f26.jpg)

Yuval R.

**Comment by MscrmTools** [comment]
Fixed in latest version
