### ISSUE TITLE
Exception when I try to view settings

### ISSUE THREAD

**Issue by rajyraman** [MscrmTools/MsCrmTools.WebResourcesManager#46]
After update I went to Windows -> Settings and saw this exception

![image](https://user-images.githubusercontent.com/5035266/41565868-01cd4efc-739c-11e8-8ac3-e2fc8016f013.png)

**Comment by MscrmTools** [comment]
I think that deleting previous settings file is the key here, as mentioned in the tweet

**Comment by MscrmTools** [comment]
Should be fixed with latest version
