### ISSUE TITLE
Critical: Cannot open tool

### ISSUE THREAD

**Issue by rajyraman** [MscrmTools/MsCrmTools.WebResourcesManager#47]
I tried to check if #46 went away after I restart XrmToolBox. Before I restarted the application, I chose the panels one by one under the Window menu. Now I cannot even open the application.

![image](https://user-images.githubusercontent.com/5035266/41565888-2881328e-739c-11e8-8adf-827259164276.png)

**Comment by rajyraman** [comment]
I went to MscrmTools.WebresourcesManager.xml in settings and changed SettingsDockState value to DockLeft from Unknown. This fixes the issue.

**Comment by MscrmTools** [comment]
Ok, I will add a check to be sure Unknown is not a possible value for settings file.
Thanks

**Comment by MscrmTools** [comment]
New version released should fix the issue
