### ISSUE TITLE
Issue replacing file and folder contents sync

### ISSUE THREAD

**Issue by mdocter** [MscrmTools/MsCrmTools.WebResourcesManager#48]
Hi Tanguy,

I encounter an issue with the new update and have a question:

1. File > Replace with new file, doesn't update the Editor, so local changes aren't visible. After the replace, previously I could 'Save' the file and the 'Pending updates' window would list the changed files to Upload and Publish. Now the file change doesn't get noticed.
2. Previously I could replace an entire folder with the contents of a local folder via the 'Update web resources in this folder with a local folder'.  But now I get the following message: ![image](https://user-images.githubusercontent.com/796916/41589997-38c93816-73b6-11e8-874d-bf8ce168e3b4.png) but I can't discover an explanation on how to setup the sync / link with a local folder. I tried the properties window, but the 'File path' property is read-only.

Hope you can help.

Kind regards,

Maarten

**Comment by MscrmTools** [comment]
I will check the code to be sure everything is ok but:
- replace should now let the web resource in state pending for update. I removed the need to save the change first
- the sync of folder should be established as soon as you load files from disk or you save webresources to disk

Let me know if it does not work as described.

**Comment by MscrmTools** [comment]
Ok, code checked and 2 bugs found :)
I'm trying to fix them asap

**Comment by mdocter** [comment]
Thanks Tanguy! That would be great.

**Comment by MscrmTools** [comment]
I released a new version hopefully, it should fix these two issues
