### ISSUE TITLE
Custom Web Resources Not Included

### ISSUE THREAD

**Issue by MichaelCLee** [MscrmTools/MsCrmTools.WebResourcesManager#49]
All custom javascripts will not display in the tool.

**Comment by MscrmTools** [comment]
What do you call custom JavaScript?

**Comment by MscrmTools** [comment]
Sorry custom web resources

**Comment by MichaelCLee** [comment]
I have several javascript web resources that I created and have associated
with form and field actions that are not showing up in your list. Is there
a way to get them to show?

**Comment by MscrmTools** [comment]
They should show up... can you provide one for example of webresource name that does not show up?

**Comment by MscrmTools** [comment]
If thèse web resources are managed, you must define in Settings that you want to load them

**Comment by MscrmTools** [comment]
So can you give me a name example of one of the web resource?

**Comment by MscrmTools** [comment]
Ok, should be fixed in latest release
