### ISSUE TITLE
Receiving error in XML Document(1,40) after upgrading to XrmToolBox v1.2018.6.24

### ISSUE THREAD

**Issue by crexin** [MscrmTools/MsCrmTools.WebResourcesManager#50]
After upgrading to XrmToolBox for Microsoft Dynamics CRM/365 CE (v1.2018.6.24) and Webresources Manager, 2.2018.6.3, I'm receiving the error below trying to open WebResources Manager noting that other XrmToolbox plugins are still working:

"An error occured when trying to display this plugin:  There is an error in XML document (1,40)."

**Comment by MscrmTools** [comment]
Please delete current webresources manager settings file and you will be good

**Comment by kschepperly** [comment]
I was also getting this same error message after updating to XrmToolBox v1.2018.6.25 with Webresources Manager v2.2018.6.3. After following your instructions to delete the MsCrmTools.WebResourcesManager.xml file, it solved my issue.

**Comment by crexin** [comment]
Thanks mscrmtools and kschepperly.  I was able to delete the MscrmTools.WebResourcesManager.xml file from %appdata%\MSCRMTools\XrmToolBox and have it work again.  You can close this issue.
