### ISSUE TITLE
Crashing on start up, Web resource version 2.2018.6.3

### ISSUE THREAD

**Issue by Divjyot1** [MscrmTools/MsCrmTools.WebResourcesManager#51]
![error web resource](https://user-images.githubusercontent.com/36576126/42218933-d1127010-7ee7-11e8-90ce-176ecd3f12b9.png)
Please find error screenshot above, thanks.

**Comment by MscrmTools** [comment]
Please delete webresources manager settings file and you should be good

**Comment by Divjyot1** [comment]
It worked, Thanks :) 
Path to delete file : C:\Users\xxx\AppData\Roaming\MscrmTools\XrmToolBox\Settings\MsCrmTools.WebResourcesManager.xml
