### ISSUE TITLE
An error *occured* when trying to display this plugin

### ISSUE THREAD

**Issue by themike10452** [MscrmTools/MsCrmTools.WebResourcesManager#52]
After updating to latest version I was greeted with this message
![image](https://user-images.githubusercontent.com/7006763/42275044-963cb634-7f97-11e8-9b74-9e92eedd73ae.png)

Deleting the settings xml file (XrmToolBox/Settings/MscrmTools.WebresourcesManager.xml) fixed the problem. This change of settings xml format needs to be handled better.

Here's my old settings file:
`<?xml version="1.0" encoding="utf-8"?>
<Options xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <LastFolderUsed>C:\Users\DELL\Desktop\New folder (4)</LastFolderUsed>
  <SaveOnDisk>false</SaveOnDisk>
  <PushTsMapFiles>false</PushTsMapFiles>
  <AutoSaveWhenLeaving>false</AutoSaveWhenLeaving>
  <ExpandAllOnLoadingResources>false</ExpandAllOnLoadingResources>
</Options>`

**Comment by MscrmTools** [comment]
Delete settings file for this plugin and you will be good
