### ISSUE TITLE
Replace with new file does not seem to work

### ISSUE THREAD

**Issue by hjmhyl** [MscrmTools/MsCrmTools.WebResourcesManager#53]
Steps to reproduce:

1. Load webresource(js) file from a solution, open it by double click the file name in Webresources Explorer
2. Update the js file on local drive, go back to Webresources Manager
3. Go to File =>Replace with new file, select updated js file

Changes are not reflected in Webresources Manager.(No changes are detected).

XrmToolBox version v1.2018.6.25
WebResourcesManager version 2.2018.6.3

**Comment by mdocter** [comment]
I mention this issue also at point 1 in #48. The editor indeed doesn't show the updated file contents.

**Comment by MscrmTools** [comment]
ok, let me check this. it seemed to work for image, but I will check for js file
