### ISSUE TITLE
Error when adding existing file with dashes in file name as web resource and when downloading

### ISSUE THREAD

**Issue by mdocter** [MscrmTools/MsCrmTools.WebResourcesManager#54]
Hi Tanguy,

I have a pretty new v9.0.2.449 organization and I'm now finally able (after many many many years of waiting) to add/upload web resources with dashes in their names :-) Hooray!! Happy happy joy joy!!

File names & paths like `ds_secret/js/chunk-vendors.js` are now allowed!

But the Web Resources Manager doesn't like it... unforunately
When I do a 'Load Web resources from a specific solution', I get an error:

    Following files have not been loaded due to invalid name or extension:
    ds_secret/js/chunk-vendors.js

Kind regards,

Maarten

**Comment by MscrmTools** [comment]
ok, this is a change I was not aware of...

I will check how to allow this character for v9+ only

**Comment by spero-cnet** [comment]
Hi, I'm still getting this error in V9...
Following files have not been loaded due to invalid name or extension:
abc_/O2D/Webresources/help--commence-without-contract.html
abc_/O2D/WebResources/help--commercial-items.html
abc_/O2D/WebResources/help--commercial-items2.html

**Comment by mdocter** [comment]
Probably the double dash between 'help' and 'commercial'. Does it work when you replace it with a single dash?
