### ISSUE TITLE
Error when launching Webresource Manager

### ISSUE THREAD

**Issue by Edwin-VC** [MscrmTools/MsCrmTools.WebResourcesManager#56]
Long time user of XrmToolBox and the Webresource Manager. Thank you for creating and updating these time-saving tools.

Today I have updated the XRM Toolbox (v. 1.2018.7.26) and the latest version of the Webresource Manager (v. 2.2018.6.3).

Now, when I try to launch the Webresource Manager from the Plugins grid in XRMToolBox I get the following error: 

**An error occurred when trying to display this plugin: there is an error in XML document (1, 40).**

What am I doing wrong? Other users experience the same? And how can I resolve this?

Thank you again and keep up the great work!

**Comment by MscrmTools** [comment]
Please delete existing settings file for WRM. You can read closed issue to find the exact path for the settings file if you don't know where to search for it

**Comment by Edwin-VC** [comment]
Thanx guys for the quick response. Sorry I had not found the existing issue first.

For others: I ended up finding the settings file in the following location: C:\Users\<username>\AppData\Roaming\MscrmTools\XrmToolBox\Settings\MsCrmTools.WebResourcesManager.xml
