### ISSUE TITLE
Different root for small later and capital later

### ISSUE THREAD

**Issue by aboodh95** [MscrmTools/MsCrmTools.WebResourcesManager#57]
Hi,

i'm getting different files root in case the starting later size is different, and this issue happen only in the debug environment

debug environment
![image](https://user-images.githubusercontent.com/12459798/43199985-dc6e0ff2-9024-11e8-92bf-18efc3d1b08d.png)

Normal environment
 
![image](https://user-images.githubusercontent.com/12459798/43200000-ea564e72-9024-11e8-9953-06114f838319.png)

**Comment by MscrmTools** [comment]
This problem comes from the fact you did not pay attention when creating the web resource manually with different casing. 
I'm not sure this is something that Webresource Manager should handle
