### ISSUE TITLE
Handle local files that are missing extensions

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/MsCrmTools.WebResourcesManager#63]
When Getting files from CRM, they may not have an extension.  Adding an Extension means that it is a different file entirely, which isn't a good option either, because all references to that file will need to be updated.

My suggestion is that If file "new_a.js" (any valid file extension should work) has another file "new_a", it will allow for edits to "new_a.js" to update "new_a" and when it is sync'd to CRM, it will be synced as "new_a".

**Comment by MscrmTools** [comment]
Thanks for the PR
