### ISSUE TITLE
XML document error

### ISSUE THREAD

**Issue by scubaracer** [MscrmTools/MsCrmTools.WebResourcesManager#66]
Hi,
I get this error when opening the plugin.
I use xrmtoolbox version 1.2018.7.28
An error occured when trying to display this plugin: There is an error in XML document (1, 40).

**Comment by brichardson2013** [comment]
I'm experiencing the same error.

**Comment by MscrmTools** [comment]
Please remove your existing settings file for Webresources manager (there is many issues already closed about this topic)
