### ISSUE TITLE
Supporting System Libraries

### ISSUE THREAD

**Issue by yuvalrs** [MscrmTools/MsCrmTools.WebResourcesManager#67]
Dynamics 365 use internal system library web resources, one for each form. 
For example, the Account form uses a web resource /Sales/Account/Account_main_system_library.js.
These web resources are currently not loaded by the plugin.

Would it be possible to add support for these 'hidden' web resources ?
I would suggest to default for ignoring them, but provide a settings flag 
that will allow for loading these system libraries.

Yuval R.

**Comment by MscrmTools** [comment]
Not sure it is possible... a quick test seems to indicate that these web resources are not returned by a retrievemultiple operation

**Comment by yuvalrs** [comment]
It is possible.
Try the following:

var QEwebresource = new QueryExpression("webresource");
QEwebresource.ColumnSet.AddColumns("name", "displayname");
QEwebresource.AddOrder("displayname", OrderType.Ascending);
QEwebresource.Criteria.AddCondition("name", ConditionOperator.Like, "%main_system_library.js%");

or:

<fetch top="200" >
  <entity name="webresource" >
    <attribute name="name" />
    <attribute name="displayname" />
    <filter>
      <condition attribute="name" operator="like" value="%main_system_library.js%" />
    </filter>
    <order attribute="displayname" />
  </entity>
</fetch>

The following shows the query result:
![dynamics 365 system libraries](https://user-images.githubusercontent.com/5218628/45545188-47ee5280-b822-11e8-815c-b00e03938250.jpg)
