### ISSUE TITLE
An error occured when trying to display this plugin: There is an error in XML document (1, 40).

### ISSUE THREAD

**Issue by HenryJammes** [MscrmTools/MsCrmTools.WebResourcesManager#71]
On XrmToolBox v1.2018.7.28, plugin WebResources Manager v2.2018.8.5, I get the following error message when I try to open the plugin.
I've updated, uninstalled and reinstalled the "WebResources Manager" plugins but it did not fix the issue.

---------------------------
Error
---------------------------
An error occured when trying to display this plugin: There is an error in XML document (1, 40).
---------------------------
OK   
---------------------------

![image](https://user-images.githubusercontent.com/37898885/45632683-35804d00-ba9e-11e8-8a02-5d0a37b2db56.png)

**Comment by MscrmTools** [comment]
Delete your settings file for this plugin and you should be good

**Comment by HenryJammes** [comment]
Thanks! I deleted "MsCrmTools.WebResourcesManager.xml" in %APPDATA% (\MscrmTools\XrmToolBox\Settings) and it works again like a charm 👍
