### ISSUE TITLE
Can't open plugin

### ISSUE THREAD

**Issue by Net-IT-Jonathan** [MscrmTools/MsCrmTools.WebResourcesManager#76]
An error occured when trying to display this plugin: Invalid DockState: Contact can not be showed as "Unknown" or "Hidden".

**Comment by gregowens** [comment]
I stumbled into the same problem somehow. I'm not sure how I caused it (possibly related to an accidental undocking of something in the XrmToolBox UI.

**FIX:**

1. Close XrmToolBox

2. Navigate to the full path of the Webresources Manager settings file. On my machine it is here: `C:\Users\<your username>\AppData\Roaming\MscrmTools\XrmToolBox\Settings\MscrmTools.WebresourcesManager.xml`

3. Open the file and replace any instances of the word "Unknown" with "DockLeft". I updated the following nodes in my settings:
```
  <PendingUpdatesDockState>DockLeft</PendingUpdatesDockState>
  <PropertiesDockState>DockLeft</PropertiesDockState>
  <SettingsDockState>DockLeft</SettingsDockState>
  <TreeviewDockState>DockLeft</TreeviewDockState>
```

4. Reload XrmToolBox, connect to your organisation and relaunch Webresources Manager
