### ISSUE TITLE
Error loading from disk: Field extension cannot be mapped to a WebResource Type

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/MsCrmTools.WebResourcesManager#77]
I'm attempting to load use File --> Load from Disk with all items checked, I get an error popup, with no additional information: 

```
An error occured while loading webresources from disk: Field extension cannot be mapped to a webresource type
Parameter name: extension
```

I also get the error if I select just the "js" checkbox.

**Comment by daryllabar** [comment]
Looks like the issue is with the .json file.  Web Resource no like-y .json files...

**Comment by MscrmTools** [comment]
I guess this issue is gone since I merged your PR.
Doing some issue clean up
