### ISSUE TITLE
Null ref Error Loading from Disk

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/MsCrmTools.WebResourcesManager#78]
If I have a .ts file with my .js file, it errors when attempting to load from disk:

```
An error occured while loading webresources from disk:
Object reference not set to an instance of an object.
```

**Comment by daryllabar** [comment]
hmm.. with my latest changes locally, this doesn't seem to be a problem.  I'll reopen if need be.

**Comment by daryllabar** [comment]
Found the issue, pushing map files has to be on.

**Comment by MscrmTools** [comment]
I guess this issue is fixed now
