### ISSUE TITLE
Folder in Folder and Options Dialog no longer gets saved

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/MsCrmTools.WebResourcesManager#8]
The value listed for the folder doesn't get saved when XTB is closed.

![image](https://cloud.githubusercontent.com/assets/9728423/18438523/c5ec7ca0-78cf-11e6-800c-616d2c8e75fe.png)

**Comment by MscrmTools** [comment]
PullRequest merged! I close this issue
