### ISSUE TITLE
Problems refreshing folder from disk

### ISSUE THREAD

**Issue by ToHa-Its** [MscrmTools/MsCrmTools.WebResourcesManager#85]
Hi :)

I use the WebResourceManger for 3 years now and it seems like I worked a long time with an old version (for CRM 2016). My main usage of this tool was to simply upload multiple webresources from disk to CRM.
With the newest version I don't manage to achieve this. (I have a similar problem as in https://github.com/MscrmTools/MsCrmTools.WebResourcesManager/issues/48)

Could you please explain how the tool should now be used - I seem to have the wrong approach here and in the Wiki section I don't find further information.

I only want to update a few files at once and I don't want to download all webresources first (the local files might have already another state that I don't want to overwrite). I already tried to use 'File -> Load Webresource' but I seem to use files with invalid extensions (e.g no extension, .js.map and .ts) so they are not loaded (Msg: Following files have not been loaded due to invalid name or extension).

My steps with the earlier version were
1. Load webresource
2. Right-click of folder
3. Update with local files
4. Mark the files to upload and click 'Upload'

 Thanks.

**Comment by MscrmTools** [comment]
The point is : as some file does not have extensions, I cannot tell what are their type. That is why they cannot be loaded.
But it makes sense to me that if you already loaded files from CRM first, then the type is known.
I will check if I can handle this specific scenario

**Comment by daryllabar** [comment]
@ToHa-lts there seems to be a bug with refreshing of local files for TypeScript/Map Files.  Working on that now.  Makre sure you turn on the option to upload the .js and .ts files.
