### ISSUE TITLE
Error publishing Web Resources: Webresource name does not contain a valid prefix

### ISSUE THREAD

**Issue by donalmc** [MscrmTools/MsCrmTools.WebResourcesManager#90]
When I try to upload images to the default CDS solution via File | Load Web Resource, I get an error when I try to publish. I've replicated in a Dynamics solution.

![image](https://user-images.githubusercontent.com/4288638/75146432-02aaa180-56f3-11ea-9ee0-6c78a0677fa7.png)

System ServiceModeIFaultException '1[Microsoft Xmn Sdk OrganizationServiceFauttr Webresource name does not contain a valid preflk (Fault Detail is equal to Exception details: ErrorCode: 0x8004f118Message: Webresource name does not contain a valid prefix

**Comment by MscrmTools** [comment]
What is the name of the webresource you are trying to create

**Comment by donalmc** [comment]
Simple names like portfolio16.png or portfolioUCI.svg

(thanks for quick response)

**Comment by MscrmTools** [comment]
A webresource has to have a name that start with something_ (the underscore is important)

**Comment by donalmc** [comment]
ok - I was adding them to the default solution as I was getting an error adding them to a solution.
Adding a _ fixes it - thanks!
