### ISSUE TITLE
Sort Folders first?

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/MsCrmTools.WebResourcesManager#92]
[Write your comment/feedback/issue here]
Any chance the folders in the webresources explorer window can be sorted by folders first, then by name?
---
- Deployment: Online
- DB Version: 9.1.0.16845
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.5.39
- Tool Version: 2.2019.9.8

**Comment by MscrmTools** [comment]
You already posted the same issue few months ago! 😅
This is actually fixed in my dev (but not commuted yet)
I plan to release a ne version next week (this is day off in France, not turning on computer until Monday)

**Comment by MscrmTools** [comment]
This is issue number #86

**Comment by daryllabar** [comment]
That was two months ago me.  He was a completely different person.  Enjoy your day off!

**Comment by MscrmTools** [comment]
Fixed with #86
