### ISSUE TITLE
Error while loading

### ISSUE THREAD

**Issue by naveedmcp** [MscrmTools/MsCrmTools.WebResourcesManager#96]
Whenever I start XRMToolbox, I am getting the following error. I am unable to run the latest XRMToolbox version (ending with 39). The stable one I can run is version (ending with 35) where Webresource manager is not working,

![image](https://user-images.githubusercontent.com/31393621/83064811-6add8c00-a030-11ea-82cc-ac149ab56826.png)

**Comment by MscrmTools** [comment]
You need to update to latest version of XrmToolBox.

**Comment by MscrmTools** [comment]
I updated the Nuget package for WebResourcesManager so that it warns user that this new version requires latest version of XrmToolBox
