### ISSUE TITLE
Update and publish is not updating web resource

### ISSUE THREAD

**Issue by dapicella** [MscrmTools/MsCrmTools.WebResourcesManager#97]
With the latest release when I update and publish a web resource the web resource is not actually published. Even when I update and publish to a solution the file is not being updated with the latest modifications. Please let me know what other info you may need. Thanks.

**Comment by MscrmTools** [comment]
It could actually not be an issue with XrmToolBox but with the CDS itself where multiple servers are used and the webresource update is not propagated to the servers fast enough.
I can update web resources with latest version without any issue.
More over, if you see the "Publishing" progress message, that means that the SDK call to publish is actually made

**Comment by dapicella** [comment]
Thanks for the reply. Honestly it has always worked without issue but with the latest version it no longer works. I do see the publishing progress so it is making the call. Does this mean that if CDS did change then I just won't be able to use the WRM? I imagine if this is the case then it will eventually begin impacting a larger segment of users. Thanks.

**Comment by MscrmTools** [comment]
I already faced this issue but months or years ago and it was really not related to WRM...

If you can do a test on this evening => update a webresource before leaving work. Check tomorrow morning if the webresource is updated. This way, you will confirm (or not) if the problem is due to load balancing between CDS servers

**Comment by Liaison00** [comment]
I'm having this exact same issue now.  Did anyone resolve it? Updates and Publishes fine in toolbox, in dynamics its shows an updated modified date, but when I open the Text Editor in browser it is unchanged.

**Comment by MscrmTools** [comment]
It really looks like a caching issue with Dynamics
