### ISSUE TITLE
Cannot open tool. Message "Invalid DockState: Content cannot be showed as 'Unknown ' or 'Hidden'"

### ISSUE THREAD

**Issue by carlvar** [MscrmTools/MsCrmTools.WebResourcesManager#99]
XRM Toolbox v 1.2020.6.40
Web Resources Manager 2.2020.5.12
Right after open XrmToolbox, o matter if connected or not to any environment, if I click on Web Resources Manager an error dialog raises:
![image](https://user-images.githubusercontent.com/3496432/88056899-91680100-cb61-11ea-8fd2-4ffba570a330.png)
It only happens with Web Resources Manager plugin, other plugins work properly

**Comment by MscrmTools** [comment]
Can you delete settings file for webresource manager?

**Comment by carlvar** [comment]
It worked, thank you!
